server:
  port: 8080

spring:
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rent
    username: root
    password: mysql
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  liquibase:
    change-log: classpath:db/db.changelog-master.yml

  jackson:
    default-property-inclusion : NON_NULL
