server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rent
    username: root
    password: mysql
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog.yml
